export const SCORE_THRESHOLD_COMPROMISED = 55
export const SCORE_THRESHOLD_LOW = 65
export const SCORE_THRESHOLD_MODERATE = 70
export const SCORE_THRESHOLD_GOOD = 80
export const SCORE_THRESHOLD_EXCELLENT = 85
export const SCORE_THRESHOLD_OPTIMAL = 95

export const STRESS_RISK_THRESHOLD = SCORE_THRESHOLD_LOW
export const INFLAMMATION_RISK_THRESHOLD = SCORE_THRESHOLD_LOW
export const COGNITION_RISK_THRESHOLD = SCORE_THRESHOLD_LOW

export const SLEEP_RISK_THRESHOLD = SCORE_THRESHOLD_MODERATE
export const RECOVERY_RISK_THRESHOLD = SCORE_THRESHOLD_MODERATE
export const LONGEVITY_RISK_THRESHOLD = SCORE_THRESHOLD_MODERATE

export const LONGEVITY_OPTIMIZED_THRESHOLD = SCORE_THRESHOLD_GOOD
export const BIOLOGICAL_STATUS_STABLE_THRESHOLD = SCORE_THRESHOLD_MODERATE
export const BIOLOGICAL_STATUS_ELEVATED_THRESHOLD = SCORE_THRESHOLD_COMPROMISED
